### ISSUE TITLE
Tratamento de erros

### ISSUE THREAD

**Issue by rafall** [rafall/compiladores_2015.1#1]
- Tratar os seguintes erros:
- Tamanho de inteiro
- Tamanho de identificador
- Números mal formados
- Caracteres inexistentes
- ID mal formado

**Comment by pivagb** [comment]
Erros tratados:
    \* Tamanho de inteiro
    \* Tamanho de ID
    \* Número inteiro mal formado
    \* Número real mal formado
    \* Comentário em linha mal acabado
    \* Caracter inexistente
